#! /bin/bash

cd lib-common
sudo npm link

cd ../lib-client
npm link lib-common

cd ../lib-server
npm link lib-common


cd ../lib-client
sudo npm link

cd ../test-server
npm link lib-server


cd ../lib-server
sudo npm link

cd ../test-server
npm link lib-server